sudo: required

language: php

php:
    - 5.5

services:
  - docker
  - mysql

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit

after_success:
  - "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD"
  - "docker build -t $DOCKER_USER/polytech-cinema-server ."
  - "docker push $DOCKER_USER/polytech-cinema-server"
